apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: game-server
  region: ap-northeast-2
managedNodeGroups:
  - name: game-server-spot-xl-v2
    instanceTypes:
      - m6i.xlarge
      - m5.xlarge
      - c6i.xlarge
      - c5.xlarge
    spot: true
    desiredCapacity: 3
    minSize: 3
    maxSize: 6
    privateNetworking: true
    labels:
      opsia.dev/game-pool: high-capacity
    nodeRepairConfig:
      enabled: true
