import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";

test("game server executes upstream Game/gameServer and serves the upstream PixiJS client", async () => {
  const config = await readFile(join(process.cwd(), "upstream-survev/config.ts"), "utf8");
  assert.match(config, /\{ mapName: "faction", teamMode: TeamMode\.Solo, enabled: true \}/);
  assert.match(config, /database:\s*\{\s*enabled: false/s);
  const faction = await readFile(join(process.cwd(), "upstream-survev/shared/defs/maps/factionDefs.ts"), "utf8");
  assert.match(faction, /maxPlayers: 100/);
  assert.match(faction, /factionMode: true/);
  const gameServer = await readFile(join(process.cwd(), "upstream-survev/server/src/gameServer.ts"), "utf8");
  const game = await readFile(join(process.cwd(), "upstream-survev/server/src/game/game.ts"), "utf8");
  const client = await readFile(join(process.cwd(), "upstream-survev/client/src/main.ts"), "utf8");
  const audioManager = await readFile(join(process.cwd(), "upstream-survev/client/src/audioManager.ts"), "utf8");
  const clientCss = await readFile(join(process.cwd(), "upstream-survev/client/css/game.css"), "utf8");
  const clientHtml = await readFile(join(process.cwd(), "upstream-survev/client/index.html"), "utf8");
  const gameClient = await readFile(join(process.cwd(), "upstream-survev/client/src/game.ts"), "utf8");
  const serverClient = await readFile(join(process.cwd(), "upstream-survev/server/src/game/client.ts"), "utf8");
  const opsiaRuntime = await readFile(join(process.cwd(), "upstream-survev/server/src/opsia/runtime.ts"), "utf8");
  const deadBodies = await readFile(join(process.cwd(), "upstream-survev/server/src/game/objects/deadBody.ts"), "utf8");
  const loot = await readFile(join(process.cwd(), "upstream-survev/server/src/game/objects/loot.ts"), "utf8");
  const player = await readFile(join(process.cwd(), "upstream-survev/server/src/game/objects/player.ts"), "utf8");
  const adminUi = await readFile(join(process.cwd(), "services/ops-console/web/src/GameAdminConsole.tsx"), "utf8");
  const adminCss = await readFile(join(process.cwd(), "services/ops-console/web/src/globals.css"), "utf8");
  const adminHtml = await readFile(join(process.cwd(), "services/ops-console/web/index.html"), "utf8");
  const docker = await readFile(join(process.cwd(), "services/game-server/Dockerfile"), "utf8");
  assert.match(gameServer, /new GameServer\(\)/);
  assert.match(gameServer, /app\.ws<GameSocketData>\("\/play"/);
  assert.match(game, /export class Game/);
  assert.match(client, /pixi\.js-legacy/);
  assert.match(client, /matchArgs\.spectator = true/);
  assert.match(client, /opsia-watch-\$\{this\.opsiaWatchView\}/);
  assert.match(client, /this\.opsiaPlay \|\| this\.opsiaWatch/);
  assert.match(client, /type: "opsia-spectator-key"/);
  assert.match(client, /event\.stopImmediatePropagation\(\)/);
  assert.match(client, /this\.pixi\.ticker\.maxFPS = 5/);
  assert.match(client, /this\.pixi\.ticker\.maxFPS = this\.opsiaWallFps/);
  assert.match(client, /__opsiaDriveSpectatorFrame/);
  assert.match(client, /this\.pixi\?\.ticker\.stop\(\)/);
  assert.match(client, /this\.pixi\?\.ticker\.update\(performance\.now\(\)\)/);
  assert.ok(clientHtml.includes("else if (/^\\/watch\\/room-\\d+\\/?$/.test(opsiaPath))"));
  assert.match(clientHtml, /`opsia-watch-\$\{opsiaWatchView\}`/);
  assert.ok(clientHtml.indexOf("opsia-watch-${opsiaWatchView}") < clientHtml.indexOf("css/app.css"));
  assert.match(audioManager, /forcedMute = this\.permanentlyMuted/);
  assert.match(audioManager, /this\.forcedMute = this\.permanentlyMuted \|\| mute/);
  assert.match(audioManager, /if \(this\.permanentlyMuted\) \{\s*this\.preloadedSounds = true;\s*return;/s);
  assert.match(client, /const rendererRes = this\.opsiaWatch\s*\? 0\.7/s);
  assert.match(clientCss, /html\.opsia-watch-player #game-area-wrapper > \*/);
  assert.match(clientCss, /html\.opsia-watch-map #ui-game > :not\(#big-map\)/);
  assert.match(clientCss, /html\.opsia-watch:not\(\.opsia-in-game\) #cvs/);
  assert.match(gameClient, /m_opsiaMapView/);
  assert.match(serverClient, /client\.spectatorOnly = true/);
  assert.match(serverClient, /this\.spectatorOnly \|\| this\.shouldSpectateTeam\(\) \? 0\.1 : 1/);
  assert.match(opsiaRuntime, /makeOpsMapSnapshot/);
  assert.match(opsiaRuntime, /game\.map\.riverDescs/);
  assert.match(opsiaRuntime, /game\.map\.buildings/);
  assert.match(opsiaRuntime, /game\.lootBarn\.loots/);
  assert.match(opsiaRuntime, /primaryReserve: weaponReserve/);
  assert.match(opsiaRuntime, /throwableCount: player\.weapons\[3\]/);
  assert.match(adminUi, /function TacticalMap/);
  assert.match(adminUi, /function ActualGameMap/);
  assert.doesNotMatch(adminUi, /function roomMapUrl/);
  assert.match(adminUi, /function drawLiveMap/);
  assert.match(adminUi, /LiveMapCanvas/);
  assert.match(adminUi, /ResizeObserver/);
  assert.match(adminUi, /room\.mapLayout/);
  assert.match(adminUi, /className="actual-game-map"/);
  assert.match(adminUi, /"--player-x": player\.x/);
  assert.match(adminUi, /"--player-y": player\.y/);
  assert.match(adminCss, /transition: transform 360ms linear/);
  assert.match(adminCss, /will-change: transform/);
  assert.match(adminUi, /function roomWatchUrl/);
  assert.match(adminUi, /wallFps/);
  assert.match(adminUi, /url\.searchParams\.set\("target", player\.id\)/);
  assert.match(adminUi, /function PlayerSpectatorView/);
  assert.match(adminUi, /function SpectatorWall/);
  assert.match(adminUi, /\(\[1, 4, 16\] as const\)/);
  assert.match(adminUi, /direction \* spectatorViewCount/);
  assert.match(adminCss, /\.spectator-wall\[data-layout="16"\]/);
  assert.match(adminUi, /frameWindow\?\.__opsiaDriveSpectatorFrame\?\.\(\)/);
  assert.match(adminUi, /requestAnimationFrame\(driveSpectatorFrame\)/);
  assert.match(gameClient, /m_opsiaPlayerView/);
  assert.match(gameClient, /this\.m_uiManager\.hideMiniMap\(\)/);
  assert.match(adminUi, /<iframe/);
  assert.doesNotMatch(adminUi, /allow="autoplay; fullscreen"/);
  assert.match(adminUi, /event\.key === "Tab"/);
  assert.match(adminUi, /selectAdjacentPlayer/);
  assert.match(adminUi, /data\.type !== "opsia-spectator-key"/);
  assert.match(adminUi, /event\.origin !== expectedOrigin/);
  assert.match(adminUi, /localeCompare\(right\.name, "ko"\)/);
  assert.match(adminUi, /event\.key\.toLowerCase\(\) === "m"/);
  assert.match(adminUi, /requestFullscreen\(\)/);
  assert.match(adminUi, /documentPictureInPicture/);
  assert.match(adminUi, /controller\.requestWindow/);
  assert.match(adminUi, /createPortal\(liveStage, pipSession\.container\)/);
  assert.match(adminUi, /world-stage\$\{isInlinePip \? " is-inline-pip" : ""\}/);
  assert.match(adminCss, /\.room-preview \{[^}]*aspect-ratio: 1;/s);
  assert.match(adminCss, /\.world-stage\.is-inline-pip \{[^}]*aspect-ratio: 1;/s);
  assert.match(adminUi, /controlPlaneClient\.addBots/);
  assert.match(adminUi, /snapshotCapturedAt > 0/);
  assert.doesNotMatch(adminUi, /ROOM_FORM_DEFAULTS|ManagementTab|Deployment|Pod|Redis/);
  assert.doesNotMatch(adminUi, /map-previews|<img/);
  assert.doesNotMatch(adminHtml, /survev-control-theme|prefers-color-scheme/);
  assert.match(adminHtml, /name="color-scheme" content="light"/);
  assert.match(adminCss, /--bg: #fafafc/);
  assert.match(adminCss, /--blue: #0a84ff/);
  const roomCard = adminUi.slice(adminUi.indexOf("function RoomCard"), adminUi.indexOf("function RoomDirectory"));
  assert.match(roomCard, /<LiveRoomMiniMap room=\{room\}/);
  assert.doesNotMatch(roomCard, /<iframe/);
  assert.match(deadBodies, /DEAD_BODY_TTL_SECONDS = 18/);
  assert.match(deadBodies, /this\.ageSeconds >= DEAD_BODY_TTL_SECONDS/);
  assert.match(loot, /cleanupAfterSeconds/);
  assert.match(player, /markForCleanupSince\(deathLootStartIndex, 30\)/);
  assert.match(docker, /WORKDIR \/app\/upstream-survev\/server/);
  assert.match(docker, /CMD \["node", "--enable-source-maps", "dist\/gameServer\.js"\]/);
  assert.doesNotMatch(docker, /services\/game-server\/src\/main/);
});

test("the three room pods run distinct validated maps", async () => {
  const gameServer = await readFile(join(process.cwd(), "upstream-survev/server/src/gameServer.ts"), "utf8");
  const roomConfig = await readFile(join(process.cwd(), "services/game-server/survev-config.hjson"), "utf8");
  const compose = await readFile(join(process.cwd(), "docker-compose.yml"), "utf8");
  const statefulSet = await readFile(join(process.cwd(), "deploy/k8s/base/game.yaml"), "utf8");

  assert.match(gameServer, /z\.enum\(\["faction", "desert", "snow"\]\)/);
  assert.match(gameServer, /process\.env\.OPSIA_MAP_NAME \?\? "faction"/);
  assert.match(gameServer, /server\.manager\.newGame\(opsiaMode\)/);
  assert.match(gameServer, /modes: process\.env\.OPSIA_ROOM === "true" \? \[opsiaMode\] : Config\.modes/);
  assert.match(gameServer, /mapName: opsiaMapName/);
  assert.match(gameServer, /mode: opsiaModeLabel/);
  assert.match(gameServer, /maxPlayers: opsiaMaxPlayers/);
  for (const mapName of ["faction", "desert", "snow"]) {
    assert.match(roomConfig, new RegExp(`mapName: "${mapName}"`));
    assert.match(compose, new RegExp(`OPSIA_MAP_NAME: ${mapName}`));
    assert.match(statefulSet, new RegExp(`export OPSIA_MAP_NAME=${mapName}`));
  }
});
